
# tap repositories and their packages

tap homebrew/core
brew aom
brew asdf
brew autoconf
brew automake
brew aws-vault
brew brotli
brew ca-certificates
brew caddy
brew cairo
brew coreutils
brew dnscrypt-proxy
brew eva
brew eza
brew fontconfig
brew freetype
brew fribidi
brew fswatch
brew gd
brew gdk-pixbuf
brew gettext
brew gh
brew giflib
brew glib
brew gmp
brew gnupg
brew gnutls
brew graphite2
brew graphviz
brew gts
brew hadolint
brew harfbuzz
brew highway
brew icu4c
brew imath
brew jasper
brew jpeg-turbo
brew jpeg-xl
brew jq
brew krb5
brew libassuan
brew libavif
brew libevent
brew libgcrypt
brew libgit2
brew libgpg-error
brew libidn2
brew libksba
brew libnghttp2
brew libpng
brew librsvg
brew libsodium
brew libssh2
brew libtasn1
brew libtiff
brew libtool
brew libunistring
brew libusb
brew libuv
brew libvmaf
brew libvterm
brew libx11
brew libxau
brew libxcb
brew libxdmcp
brew libxext
brew libxrender
brew libyaml
brew little-cms2
brew llvm@15
brew lpeg
brew luajit
brew luv
brew lz4
brew lzo
brew m4
brew make
brew mpdecimal
brew msgpack
brew neovim
brew netpbm
brew nettle
brew npth
brew nspr
brew nss
brew oniguruma
brew openexr
brew openssl@3
brew p11-kit
brew pango
brew pcre2
brew pinentry
brew pixman
brew postgresql@15
brew python@3.12
brew readline
brew redis
brew rush-parallel
brew shellcheck
brew sqlite
brew starship
brew tree-sitter
brew unbound
brew unibilium
brew unixodbc
brew webp
brew xorgproto
brew xz
brew zstd

tap homebrew/cask
cask bruno
cask discord
cask docker
cask evkey
cask firefox
cask font-hack-nerd-font
cask fork
cask google-drive
cask iterm2
cask jetbrains-toolbox
cask logi-options+
cask notion
cask notion-calendar
cask obsidian
cask rectangle
cask visual-studio-code
cask zoom

tap homebrew/bundle

tap homebrew/services

tap heroku/brew
brew heroku

tap rcmdnk/file
brew brew-file

# App Store applications
appstore 682658836 GarageBand (10.4.8)
appstore 408981434 iMovie (10.3.9)
appstore 409183694 Keynote (14.1)
appstore 409203825 Numbers (14.1)
appstore 409201541 Pages (14.1)
