
# tap repositories and their packages

tap homebrew/core
brew ca-certificates
brew eza
brew gettext
brew libgit2
brew libssh2
brew libuv
brew libvterm
brew lpeg
brew luajit
brew luv
brew make
brew msgpack
brew neovim
brew openssl@3
brew starship
brew tree-sitter
brew unibilium

tap homebrew/cask
cask discord
cask evkey
cask firefox
cask font-hack-nerd-font
cask fork
cask iterm2
cask logi-options+
cask notion
cask notion-calendar
cask obsidian
cask rectangle
cask visual-studio-code
cask zoom

tap homebrew/bundle

tap rcmdnk/file
brew brew-file

# Other Cask applications
cask logi-options-plus
